export default {
  locale: 'th',
  messages: {
    headerDescription: 'รวมบริษัทTechในกรุงเทพฯ ศึกษาสภาพแวดล้อมการทำงานและวัฒนธรรมบริษัทได้ที่นี่',
    requestListButton: 'สร้าง emplist ให้บริษัทของคุณ',
    requestListHeader: 'คนเก่งใส่ใจกับบรรยากาศการทำงานที่ดี และวัฒนธรรมการทำงานที่เข้ากับพวกเค้า. ทำให้คนเก่งเหล่านั้นได้รู้จักกับบริษัทคุณ และทำไมพวกเค้าถึงอยากทำงานกับคุณ. 1 บริษัท มี 1 emplist ได้ฟรี และลิสจะถูกแสดงบนเว็บไซต์เราตลอดกาล',
    rlp_titleDesc: 'ใช้ความคิดสร้างสรรค์ได้เต็มที่ในการสร้าง title ให้กับ emplist คุณ ! (มากสุด 140 ตัวอักษร)',
    rlp_skillsDesc: 'สกิลที่ต้องการทั้งหมดสำหรับตำแหน่งงานทีเปิดรับอยู่ เช่น Javascript, Clojure (อย่างน้อย 1 มากสุด 7)',
    rlp_expDesc: 'ช่วงประสบการณ์ที่ต้องการสำหรับตำแหน่งงานที่เปิดรับอยู่',
    rlp_salaryDesc: 'ไม่ระบุได้ แต่แนะนำให้ระบุ',
    rlp_detailsDesc: 'แนะนำบริษัทของคุณ เล่าถึงวัฒนธรรมและบรรยากาศการทำงานในบริษัท ตัวอย่างเพื่อนร่วมงานที่จะได้เจอ blog ของบริษัท ตำแหน่งงานทั้งหมดที่เปิดรับอยู่ ข้อเสนอ และอื่นๆ (ใช้ความคิดสร้างสรรค์กับ editor ของเราได้เต็มที่ !)',
    rlp_howToApplyDesc: 'ต.ย. ส่ง resume ของคุณเข้ามาที่อีเมลนี้ หรือเข้าไปที่เว็บสมัครงานของบริษัท',
    rlp_locationDetailDesc: 'ต.ย. ใกล้ BTS Foo, ในอาคาร Bar',
    rlp_emailDesc: 'ในกรณีที่เราต้องติดต่อคุณ !',
    rlp_passwordDesc: 'สำหรับการจัดการ emplist ของคุณ',
    doneRequestDesc1: 'Successfully sending request ! we will send you checking result via your email in 24 hours.',
    doneRequestDesc2: 'We want to make finding jobs and talents easier for everyone and also hopefully inspire kids how great tech workplace and its environment are so they will work hard to get in their dream workplace and finally contribute to fighting talents shortage problem in Thai tech industry. So please suggest Emplist to your colleagues so that more people can find the right workplace easier. (which increase your chance of finding the right candidate too!)',
    drlp_completing: 'กำลังส่งคำร้องขอ..',
    drlp_err: 'โอ๊ะ! ดูเหมือนว่าจะมีข้อผิดพลาด.. กรุณาติดต่อมาที่ hi.emplist@gmail.com เพื่อที่เราจะได้แก้ปัญหานี้ให้กับคุณ !',
  },
};
